# Note: This image can be found in build/pipelines/docker-image
image: atlassianlabs/atlaskit-mk-2:1.0.4
# This ensures we do a full clone on each build which prevents issues when cross referencing
# changesets and releases
clone:
  depth: full
options:
  size: 2x

pipelines:
  custom:
    # This will run with the visual regression tool
    build-visual-regression:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - source ./build/visual-regression/getDockerCompose.sh
            - pwd
            - ls
            - ls -Rla /opt/atlassian/pipelines/agent/build/node_modules/
            - cat /opt/atlassian/pipelines/agent/build/node_modules/jest-puppeteer-docker/docker-compose.yml
            - yarn test:vr
          caches:
            - node
          services:
            - docker
     