#!/bin/sh


echo "### custom post-checkout"

changedFiles="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

echo "Changed files: $changedFiles"

runOnChange() {
	echo "$changedFiles" | grep -q "$1" && eval "$2"
}

echo "### Check whether yarn.lock has changed, and if so run package manager..."

# If dependencies have changed, rerun package manager to install latest deps.
runOnChange yarn.lock "bolt"
