// DO NOT EDIT THIS FILE DIRECTLY!
// This file was auto generated and may be overritten.
// To make changes, use the generator.

export const decision =
  'decision-0b6f4b2a68be2f8c6bb77710b1b49535dafebc2b3bc5a409cacb8c08190c0f38';
