// DO NOT EDIT THIS FILE DIRECTLY!
// This file was auto generated and may be overritten.
// To make changes, use the generator.

export const info =
  'info-5b814a996410f2c610abe1fbbb7352d2a3e00303b665f5a19f14e0efc46a3421';
