// DO NOT EDIT THIS FILE DIRECTLY!
// This file was auto generated and may be overritten.
// To make changes, use the generator.

export const taskItemChecked =
  'taskItemChecked-824889cb3ff64e07de59972449ac40a0b5a95f420a91eebc336a26a9fb9ff1c8';
