// DO NOT EDIT THIS FILE DIRECTLY!
// This file was auto generated and may be overritten.
// To make changes, use the generator.

export const taskItemUnchecked =
  'taskItemUnchecked-49eeeed294c361f194a0c7532a9fea5ed801e95f696d2f271274d96d1594fdc6';
