// DO NOT EDIT THIS FILE DIRECTLY!
// This file was auto generated and may be overritten.
// To make changes, use the generator.

export const tip =
  'tip-84f7194d01ba14a3e65e4837fade71b550a9695334651f929b6c9f905e9a133c';
