// DO NOT EDIT THIS FILE DIRECTLY!
// This file was auto generated and may be overritten.
// To make changes, use the generator.

export const warning =
  'warning-d7e63880cf8f3a7ec294fc6458e021cc1b3593e1d3631bb2fb25299a668e74c3';
